name: Wiki-As-Readme As Action

on:
  # 1. When pushing to main branch (runs automatically with defaults)
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'WIKI.md'
      - '.github/workflows/WIKI-AS-README-AS-ACTION.yml'
  
  # 2. Manual trigger (allows custom input settings)
  # "Use workflow from" menu in GitHub UI handles branch selection automatically.
  workflow_dispatch:
    inputs:
      language:
        description: 'Language code (e.g., ko, en, ja, etc.)'
        required: false
        default: 'en'
      llm_provider:
        description: 'LLM Provider (google, openai, anthropic, etc.)'
        required: false
        default: 'google'
      model_name:
        description: 'Model Name'
        required: false
        default: 'gemini-2.5-flash'
      sync_to_notion:
        description: 'Sync to Notion? (true/false)'
        type: boolean
        required: false
        default: false
      commit_method:
        description: 'How to apply changes'
        type: choice
        options:
          - push
          - pull-request
        default: 'push'

jobs:
  wiki-time:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    env:
      WIKI_OUTPUT_PATH: "WIKI.md"

    steps:
      # 1. Checkout code
      # No 'ref' needed; it automatically checks out the branch selected in the "Run workflow" UI.
      - name: Checkout code
        uses: actions/checkout@v4

      # -----------------------------------------------------------------------
      # [OPTIONAL] GCP Credentials Setup
      # Create GCP key only if using Google Provider (defaults to 'google' if undefined)
      # -----------------------------------------------------------------------
      - name: Create GCP Credentials File
        if: ${{ (inputs.llm_provider == 'google') || (inputs.llm_provider == '') || (github.event_name == 'push') }}
        env:
          GCP_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          if [ -n "$GCP_KEY" ]; then
            echo "$GCP_KEY" > ./gcp-key.json
          else
            echo "::warning::GOOGLE_APPLICATION_CREDENTIALS secret is missing, but provider is set to google."
          fi

      # 2. Generate Wiki Content & Sync
      - name: Generate Content (and Sync to Notion if enabled)
        uses: docker://ghcr.io/catuscio/wiki-as-readme-action:latest
        env:
          # --- Basic Settings ---
          # Use input if available, otherwise default to 'en' (e.g., for push events)
          LANGUAGE: ${{ inputs.language || 'en' }}
          WIKI_OUTPUT_PATH: ${{ env.WIKI_OUTPUT_PATH }}
          
          # --- LLM Provider and Model Settings ---
          LLM_PROVIDER: ${{ inputs.llm_provider || 'google' }}
          MODEL_NAME: ${{ inputs.model_name || 'gemini-2.5-flash' }}
          
          # --- API Key Settings ---
          
          # [GCP / Vertex AI]
          GCP_PROJECT_NAME: ${{ secrets.GCP_PROJECT_NAME }}
          GCP_MODEL_LOCATION: ${{ secrets.GCP_MODEL_LOCATION }}
          GOOGLE_APPLICATION_CREDENTIALS: /github/workspace/gcp-key.json
          
          # [Other Providers]
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # --- GitHub Token ---
          GIT_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # --- Notion Sync Settings ---
          # Pass "true" only if inputs.sync_to_notion is true; otherwise "false" (including push events)
          NOTION_SYNC_ENABLED: ${{ inputs.sync_to_notion || 'false' }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

      # -----------------------------------------------------------------------
      # [OPTIONAL] GCP Credentials Cleanup
      # -----------------------------------------------------------------------
      - name: Remove GCP Credentials File
        if: always()
        run: rm -f ./gcp-key.json

      # 3. Commit and Push Changes (Update file in GitHub Repo)
      # Option A: Direct Push (default for push events or when 'push' is selected)
      - name: Commit and Push changes
        if: ${{ inputs.commit_method == 'push' || github.event_name == 'push' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "✨📚 Update ${{ env.WIKI_OUTPUT_PATH }} via Wiki-As-Readme Action (${{ inputs.language || 'en' }})"
          file_pattern: ${{ env.WIKI_OUTPUT_PATH }}

      # Option B: Create Pull Request (when 'pull-request' is selected)
      - name: Create Pull Request
        if: ${{ inputs.commit_method == 'pull-request' }}
        uses: peter-evans/create-pull-request@v7
        with:
          title: "✨📚 Update ${{ env.WIKI_OUTPUT_PATH }} via Wiki-As-Readme Action"
          body: |
            This PR was automatically generated by [Wiki-As-Readme](https://github.com/catuscio/wiki-as-readme) Action.
            
            It includes the following changes:
            - Updated wiki content in **${{ env.WIKI_OUTPUT_PATH }}** based on the current state of the repository.
            - (If enabled) Synchronized changes to the linked Notion database.            

            ---

            > 📖 Powered by [Wiki-As-Readme](https://github.com/catuscio/wiki-as-readme)
            > Turn your codebase into a comprehensive Wiki in minutes, delivered in a single Readme.
            > Works with Any Model. Any Repo. Any Environment.
          branch: wiki-update-${{ github.run_id }}
          commit-message: "✨📚 Update ${{ env.WIKI_OUTPUT_PATH }} via Wiki-As-Readme Action (${{ inputs.language || 'en' }})"
          add-paths: ${{ env.WIKI_OUTPUT_PATH }}