name: Manual Wiki Sync to Notion

on:
  workflow_dispatch:
    inputs:
      language:
        description: 'Language code (e.g., ko, en, ja)'
        required: false
        default: 'ko'
      llm_provider:
        description: 'LLM Provider (google, openai, anthropic)'
        required: false
        default: 'google'
      model_name:
        description: 'Model Name'
        required: false
        default: 'gemini-2.5-flash'

jobs:
  generate-and-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Only read permissions needed since we are syncing to Notion, not committing back

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -----------------------------------------------------------------------
      # [OPTIONAL] GCP Credentials Setup
      # Remove or comment out this step if you are NOT using Google Cloud (Vertex AI).
      # -----------------------------------------------------------------------
      - name: Create GCP Credentials File
        if: ${{ inputs.llm_provider == 'google' }}
        env:
          GCP_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          if [ -n "$GCP_KEY" ]; then
            echo "$GCP_KEY" > ./gcp-key.json
          else
            echo "GOOGLE_APPLICATION_CREDENTIALS secret is missing!"
            exit 1
          fi

      # 1. Generate Wiki Content & Sync to Notion
      - name: Generate Wiki & Sync to Notion
        uses: docker://ghcr.io/catuscio/wiki-as-readme-action:latest
        env:
          # --- Basic Settings ---
          LANGUAGE: ${{ inputs.language }}
          OUTPUT_FILE: "WIKI.md" # Required for generation, even if just syncing
          
          # --- LLM Provider and Model Settings ---
          LLM_PROVIDER: ${{ inputs.llm_provider }}
          MODEL_NAME: ${{ inputs.model_name }}
          
          # --- API Key Settings ---
          
          # [GCP / Vertex AI]
          GCP_PROJECT_NAME: ${{ secrets.GCP_PROJECT_NAME }}
          GCP_MODEL_LOCATION: ${{ secrets.GCP_MODEL_LOCATION }}
          GOOGLE_APPLICATION_CREDENTIALS: /github/workspace/gcp-key.json
          
          # [Other Providers]
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # --- GitHub Token ---
          GIT_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # --- Notion Sync Settings ---
          NOTION_SYNC_ENABLED: "true"
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

      # -----------------------------------------------------------------------
      # [OPTIONAL] GCP Credentials Cleanup
      # -----------------------------------------------------------------------
      - name: Remove GCP Credentials File
        if: always()
        run: rm -f ./gcp-key.json
